### ISSUE TITLE
Support Other Heart Rate MOnitors

### ISSUE THREAD

**Issue by mrdeadlocked** [Eryux/miband-heartrate#9]
I like how the apps looks compared to some others. Would it be possible to support other BLE heart rate monitors?

**Comment by Eryux** [comment]
The software support Mi Band 2 and 4, other version of the Mi Band might work but I don't have other band to test. 

Depending of the heart rate device. BLE heart rate service is mostly standardized but the problem is the authentication/access proccess that is different between manufacturers/devices and most of them are closed to public.

Maybe I will add other devices to the software if I change my band and find time to work on it. But for this app, I think, it would only stay compatible with xiaomi mi band

**Comment by mrdeadlocked** [comment]
No worries. I have a CooSpo Heart rate monitor. I can see it in the dropdown but it doesn't function. I appreciate the quick response.

**Comment by erralp** [comment]
also. band 3 works perfect. thanks 
![hrm3](https://user-images.githubusercontent.com/89088538/129746511-690ece9c-e33f-4bf1-8884-9898bc6dd3c0.jpg)

**Comment by Eryux** [comment]
> 
> 
> also. band 3 works perfect. thanks
> ![hrm3](https://user-images.githubusercontent.com/89088538/129746511-690ece9c-e33f-4bf1-8884-9898bc6dd3c0.jpg)

Thank you for notifying, which model do you select when connecting your Mi Band 3 to make it work ?

**Comment by erralp** [comment]
> 
> 
> > also. band 3 works perfect. thanks
> > ![hrm3](https://user-images.githubusercontent.com/89088538/129746511-690ece9c-e33f-4bf1-8884-9898bc6dd3c0.jpg)
> 
> Thank you for notifying, which model do you select when connecting your Mi Band 3 to make it work ?

Mi band 2.
